### ISSUE TITLE
Implement Grant Management API

### ISSUE THREAD

**Issue by jokk-itu** [jokk-itu/authserver-framework#4]
## Problem

The Grant Management Specification is not implemented.

## Solution

Implement as specified in the [OpenId Specification](https://openid.net/specs/oauth-v2-grant-management-ID1.html)

### Discovery
grant_management_actions_supported = ['revoke', 'query', 'replace', 'merge', 'create']
grant_management_endpoint = ISSUER/connect/grant
grant_management_action_required = boolean

- [x] DiscoveryDocumentOptions

### Scope
Add two new scopes.

grant_management_query
grant_management_revoke

### Token Endpoint
Return the GrantId as a response property during grant_type authorization_code and refresh_token.
Not for client_credentials, as that is not part of OpenId.

- [x] AuthorizationCodeRequestValidator
- [x] AuthorizationCodeRequestProcessor
- [x] RefreshTokenRequestValidator
- [x] RefreshTokenRequestProcessor
- [x] Endpoint integration tests

### Grant Revoke Endpoint
Create a Delete endpoint which takes a grant_id as a path variable and an access_token in the Authorization header.
Functionality is to revoke the Grant and all tokens must also be revoked.

Response 204 if successful.
Response 404 if no grant is found by grant_id.
Response 403 if client is unauthorized.
Response 401 if access token is invalid.

- [x] GrantManagementRevokeRequestValidator
- [x] GrantManagementRevokeRequestProcessor
- [x] Endpoint integration tests

### Grant Query Endpoint
Create a Get endpoint which takes a grant_id as a path variable and an access_token in the Authorization header.

Response contains the following properties.
scopes: array of Scope
Scope: string of scope, array of strings of resource uris
claims:  array of strings of OpenId claims

Response 200 if successful.
Response 404 is no grant is found by grant_id.
Response 403 if client is unauthorized
Response 401 if access token is invalid.

- [x] GrantManagementQueryRequestValidator
- [x] GrantManagementQueryRequestProcessor
- [x] Endpoint integration tests

### Authorize / Pushed Authorization

Extend the endpoins with two new parameters:
grant_management_action
grant_id

Refactor Consent into consents used for the client and consents used for the authorization grant.

- [x] SecureRequestService
- [x] AuthorizeRequestProcessor
- [x] AuthorizeRequestValidator
- [x] AuthorizeInteractionService
- [x] PushedAuthorizationValidator
- [ ] ConsentRepository
- [ ] AuthorizationGrantRepository
- [x] AuthorizeService
- [x] UserinfoRequestProcessor
- [x] IdTokenBuilder
- [x] Endpoint integration tests
